"""add onboarding_completed to users

Revision ID: be19883ddaab
Revises: 59fc5fe02285
Create Date: 2025-11-13 23:58:05.557186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be19883ddaab'
down_revision: Union[str, Sequence[str], None] = '59fc5fe02285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default='1'))

    # Set existing users to onboarding_completed = True for backwards compatibility
    op.execute("UPDATE users SET onboarding_completed = 1 WHERE onboarding_completed = 0")

    # Remove server_default after data migration
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('onboarding_completed', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
