"""move_currency_from_user_to_account

Revision ID: c01a47d1eae6
Revises: d9dd18728b45
Create Date: 2025-10-04 12:34:35.164605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01a47d1eae6'
down_revision: Union[str, Sequence[str], None] = 'd9dd18728b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(length=3), nullable=True))

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
