"""make_category_id_nullable_on_transactions

Revision ID: d42c27916139
Revises: 917fbc6f8f00
Create Date: 2025-10-01 10:11:11.684140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42c27916139'
down_revision: Union[str, Sequence[str], None] = '917fbc6f8f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('category_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###
